#+TITLE: Pyper

* What it is

  Nothing much, yet.

  The goal of this application is to serve as a tool for keeping track
  of academic papers (essentially [[https://en.wikipedia.org/wiki/Reference_management_software][Reference Management Software]]),
  their authors and how they relate to each other. It is also possible
  to tag papers.

** Functionality --- a hypothetical example

    Suppose you add a paper /Seminal Paper/ with authors /Alice/ and
    /Bob/, and that this paper is tagged with /theory/. Now, suppose
    you add another paper /Follow up Work of Seminal Paper/ with
    authors /Alice/ and /Eve/, and which contains a citation to the
    first paper.

    It should now be possible to retrieve all papers authored by
    /Alice/. Or to retrieve /Follow up Work of Seminal Paper/ and see
    all citations that is also stored in the database.
* Installation

  In so far as it can be "installation".

  Pull the repository
  : git pull https://github.com/anderspkd/pypers
  : cd pypers

  Create a virtual environment
  : python -m venv <virtual env name>

  Make sure the ~VENV~ variable in ~Makefile~ points to the virtual
  environment. By default it is set to ~venv~.

  Run the tests.
  : make test_full


* Development

  See ~TODO.org~.
